home:
    pattern: /
    defaults: { _controller: BackendBundle:Backend:example }

login:
    pattern: /login
    defaults: { _controller: BackendBundle:Backend:login }
    
oauth_procesator:
    pattern: /oauth_procesator
    defaults: { _controller: BackendBundle:Backend:oauthProcesator }
    
users:
    resource: "@BackendBundle/Resources/config/routing/admin-user.yml"
    prefix: /users/
    
api_users:
    resource: "@BackendBundle/Resources/config/routing/api_users.yml"
    prefix: /api_users/    

tasks:
    resource: "@BackendBundle/Resources/config/routing/task.yml"
    prefix: /tasks/

sprints:
    resource: "@BackendBundle/Resources/config/routing/sprint.yml"
    prefix: /sprints/
