api_users_list:
    pattern: /
    defaults: { _controller: BackendBundle:ApiUser:listApiUsers }
    
show_api_user:
    pattern: /apis_user/{id}
    defaults: { _controller: BackendBundle:ApiUser:apiUserShow }  
    
new_api_user:
    pattern: /new
    defaults: { _controller: BackendBundle:ApiUser:newApiUser }
    
edit_api_user:
    pattern: /edit/{id}
    defaults: { _controller: BackendBundle:ApiUser:editApiUser }    
    
create_api_user:
    pattern: /create
    defaults: { _controller: BackendBundle:ApiUser:createApiUser }
    
put_api_user:
    pattern: /put/{id}
    defaults: { _controller: BackendBundle:ApiUser:putApiUser }
    
delete_api_user:
    pattern: /delete/{id}
    defaults: { _controller: BackendBundle:ApiUser:deleteApiUser }    