parameters:
    admin.user.model.class: Logbook\BackendBundle\Model\Handler\AdminUserHandler
    rest.handler.class: Logbook\BackendBundle\Model\Handler\RESTHandler
    user.json.type: Logbook\BackendBundle\Form\Type\JsonUserType
    image.handler.class: Logbook\BackendBundle\Model\Handler\ImageHandler
    history.handler.class: Logbook\BackendBundle\Model\Handler\HistoryHandler
    entry.json.type: Logbook\BackendBundle\Form\Type\JsonEntryType
    expirable.action.listener.class: Logbook\BackendBundle\EventListener\ExpirableActionListener
    dental.handler.class: Logbook\BackendBundle\Model\Handler\DentalHandler

services:
    rest.handler.model:
        class: %rest.handler.class%
        arguments: [@logbook.client]    

    form.type.json.user:
        class: %user.json.type%
        arguments:
            - @rest.handler.model
            - @service_container
        tags:
            - { name: form.type, alias: json_user }

    form.type.json.entry:
        class: %entry.json.type%
        arguments:
            - @rest.handler.model
            - @service_container
        tags:
            - { name: form.type, alias: json_entry }

    expirable.action_listener:
        class: %expirable.action.listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }